name: Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore Jellyfin.Plugin.Announcements.csproj

      - name: Build
        run: dotnet build Jellyfin.Plugin.Announcements.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish Jellyfin.Plugin.Announcements.csproj -c Release -o publish --no-build
